#!/usr/bin/env bash
# This script runs the whoami command as the user passed as an argument

if id "$1" &>/dev/null; then
    sudo -u "$1" whoami
else
    echo "Error: User $1 does not exist"
    exit 1
fi
