#!/usr/bin/env bash
# This script configures Nginx to run as nginx user and listen on port 8080

# Set permissions to allow nginx to run
chmod 644 /etc/nginx/nginx.conf

# Configure nginx to run as nginx user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Configure nginx to listen on port 8080 instead of 80
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Make sure nginx user exists (it should by default, but just to be safe)
id -u nginx &>/dev/null || useradd -r nginx

# Give nginx user ownership of necessary directories
chown -R nginx:nginx /var/log/nginx

# Stop nginx if it's running
pkill nginx || true

# Start nginx as nginx user
su -s /bin/bash -c "service nginx start" nginx
