#!/usr/bin/env bash
# Install UFW
sudo apt update
sudo apt install ufw -y

# Reset UFW
sudo ufw reset

# Set default rules
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow essential ports
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Enable UFW
sudo ufw enable

# Verify status
sudo ufw status verbose
