#!/usr/bin/env bash
# Fix Apache to return "Hello Holberton" on the root page
apt-get update -y
apt-get install -y apache2
service apache2 start
echo "Hello Holberton" > /var/www/html/index.html
service apache2 restart
