#!/usr/bin/env bash
# Fixes Nginx to listen on port 80
apt-get update -y && apt-get install -y nginx && sed -i "s/listen 80 default_server;/listen 80;/g" /etc/nginx/sites-enabled/default && systemctl restart nginx
