#!/usr/bin/env bash
# Install Nginx and configure it to listen on port 80
apt-get update -y && apt-get install -y nginx && systemctl start nginx && systemctl enable nginx && sed -i "s/listen 80 default_server;/listen 80;/g" /etc/nginx/sites-enabled/default && systemctl restart nginx
