#!/usr/bin/env bash
# This script transfers a file from the client to a server using scp

# Variables from arguments
FILE_PATH="$1"
SSH_KEY_PATH="$2"
USER="ubuntu"
SERVER_IP="3.83.106.227"
DEST_PATH="/root/alu-system_engineering-devops/web_server"
# Check if arguments are provided
if [ -z "$FILE_PATH" ] || [ -z "$SSH_KEY_PATH" ]; then
    echo "Usage: $0 <file_path> <ssh_key_path>"
    exit 1
fi
# Transfer the file using scp
scp -i "$SSH_KEY_PATH" "$FILE_PATH" "$USER@$SERVER_IP:$DEST_PATH"

echo "File transfer complete."

