#!/usr/bin/env bash
# This script transfers a file from the client to a server using scp

# Variables from arguments
FILE_PATH="$1"
SSH_KEY_PATH="$2"
USER="ubuntu"
SERVER_IP="3.83.106.227"
DEST_PATH="/root/alu-system_engineering-devops/ssh"

# Check if arguments are provided
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

scp -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    -i "$4" \
    "$1" \
    "$3@$2:~/"

echo "File transfer complete."

