#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to a specific URL

apt-get update
apt-get install -y nginx

cat > /etc/nginx/sites-available/default <<'EOL'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        return 200 "Holberton School";
        add_header Content-Type text/plain;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOL

service nginx restart
